version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=capstone-archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis-dump:/var/lib/redis
  server:
    build: ./server
    container_name: server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/capstone-archive
      - REDIS_ADDRESS=redis:6379
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
      - redis
    ports:
      - 4000:8080
  client:
    build: ./client
    container_name: client
    environment:
      - REACT_APP_API_URL=http://localhost:4000/graphql
    depends_on:
      - server
    ports:
      - 3000:3000
