version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=capstone-archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 1s
      timeout: 3s
      retries: 30
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis-dump:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  server:
    build: ./server
    container_name: server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/capstone-archive
      - REDIS_ADDRESS=redis:6379
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 4000:8080
  client:
    build: ./client
    container_name: client
    environment:
      - REACT_APP_API_URL=http://localhost:4000/graphql
    depends_on:
      server:
        condition: service_healthy
    ports:
      - 3000:3000
